# Generated by Django 5.1.2 on 2024-10-30 01:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idempleado', models.CharField(max_length=1000)),
                ('nombre', models.CharField(max_length=50)),
                ('usuario', models.CharField(max_length=50)),
                ('contrasenia', models.CharField(max_length=16)),
                ('telefono', models.CharField(max_length=15)),
                ('caja', models.IntegerField()),
                ('rol', models.CharField(choices=[('ADM', 'Administrador'), ('BDG', 'Empleado Bodega'), ('CAJ', 'Empleado Caja'), ('GEB', 'Gerente de Bodega')], default='BDG', max_length=3)),
                ('idsucursal', models.CharField(choices=[('URI', 'Uriangato'), ('PURU', 'Puruandiro'), ('YURI', 'Yuriria')], default='URI', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descuento', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('stock', models.PositiveIntegerField()),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('sucursal', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='NAME', max_length=100)),
                ('numTel', models.CharField(default='000-000-0000', max_length=15)),
                ('direccion', models.CharField(default='Sin dirección', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venta_no', models.CharField(max_length=20, unique=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to='pos.empleado')),
            ],
        ),
        migrations.DeleteModel(
            name='Empleados',
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.producto'),
        ),
        migrations.AddField(
            model_name='venta',
            name='productos',
            field=models.ManyToManyField(through='pos.DetalleVenta', to='pos.producto'),
        ),
        migrations.AddField(
            model_name='venta',
            name='sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.sucursal'),
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='pos.venta'),
        ),
    ]
